(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* This notebook creates the figures for the cjSOE model *)
(* Note: The "sensitivity" figure takes about 30 mins to generate *)
(* Hence it has been "commented out"; to generate it just remove the (* *) comment delimiters *)


(* Set up the environment in which the figure-generating files can be executed *)
ClearAll["Global`*"];
If[Length[$FrontEnd] > 0,MathDir=SetDirectory[NotebookDirectory[]]];(* If running from the Notebook interface *)
If[Length[$FrontEnd] <= 0,MathDir="/Volumes/Data/Work/BufferStock/Tractable/cjSOE/Latest/software/Mathematica"];(* If not running from the Notebook interface *)
SetDirectory[MathDir];
Get["./FuncsInit.m"];
Get["./FuncsSOE.m"];
Get["./FuncsIndivProblem.m"];
figuredirectory = MathDir<>"/../../Figures/"; (* directory where the figures will be saved *)
resetParams;
calculateValues;


Get["phaseDiagMake.m"];phaseDiagMake;phaseDiag


Get["pathsMake.m"];pathsMake;paths


Get["sensitivityMake.m"];sensitivityMake;sensitivity


Get["socInsMake.m"];socInsMake;socIns


Get["transDynMake.m"];transDynMake;transDyn


Get["capOutflowsMake.m"];capOutflowsMake;capOutflows



Get["genEqbmMake.m"];genEqbmMake;genEqbm


Get["globImbMake.m"];globImbMake;globImb
